### Employee Service Test File
### Base URL: http://localhost:4004

### Aditya Mishra (Cordys)
GET http://localhost:4004/odata/v4/employee/MyProjects
Authorization: Basic aditya.mishra:initial

### Nadeem Abbas (Sony COFA)
GET http://localhost:4004/odata/v4/employee/MyProjects
Authorization: Basic nadeem.abbas:initial

### Yugal Kishore (Cordys)
GET http://localhost:4004/odata/v4/employee/MyProjects
Authorization: Basic yugal.kishore:initial

### Sumit Jhaldiyal (Sony COFA)
GET http://localhost:4004/odata/v4/employee/MyProjects
Authorization: Basic sumit.jhaldiyal:initial


# Test MyProjects
GET http://localhost:4004/odata/v4/employee/MyProjects
Authorization: Basic aditya.mishra:initial


# Test BookedHoursOverview
GET http://localhost:4004/odata/v4/employee/BookedHoursOverview
Authorization: Basic aditya.mishra:initial


# Test ProjectEngagementDuration
GET http://localhost:4004/odata/v4/employee/ProjectEngagementDuration
Authorization: Basic EMP001:password


### 1. GET - Read Employee Profile
GET http://localhost:4004/odata/v4/employee/MyProfile
Authorization: Basic aditya.mishra:initial

###

### 2. GET - Read My Timesheets
GET http://localhost:4004/odata/v4/employee/MyTimesheets
Authorization: Basic aditya.mishra:initial

###

### 3. GET - Read Available Activities (All)
GET http://localhost:4004/odata/v4/employee/AvailableActivities
Authorization: Basic aditya.mishra:initial

###

### 4. GET - Read Available Activities (Filter by Project - Cordys)
GET http://localhost:4004/odata/v4/employee/AvailableActivities?$filter=project_ID eq b47ac10b-58cc-4372-a567-0e02b2c3d500
Authorization: Basic aditya.mishra:initial

###

### 5. GET - Read Available Activities (Filter by Project - Sony COFA)
GET http://localhost:4004/odata/v4/employee/AvailableActivities?$filter=project_ID eq b47ac10b-58cc-4372-a567-0e02b2c3d501
Authorization: Basic aditya.mishra:initial

###

### 6. GET - Read Available Non-Project Types
GET http://localhost:4004/odata/v4/employee/AvailableNonProjectTypes
Authorization: Basic aditya.mishra:initial

###

### 7. GET - Read My Progress Summary
GET http://localhost:4004/odata/v4/employee/MyProgressSummary
Authorization: Basic aditya.mishra:initial

###

### 8. GET - Read My Daily Summary
GET http://localhost:4004/odata/v4/employee/MyDailySummary
Authorization: Basic aditya.mishra:initial

###

### 9. POST - Create New Timesheet (Draft)
POST http://localhost:4004/odata/v4/employee/MyTimesheets
Authorization: Basic aditya.mishra:initial
Content-Type: application/json

{
  "employee_ID": "a47ac10b-58cc-4372-a567-0e02b2c3d490",
  "workDate": "2024-11-05",
  "hoursWorked": 8.0,
  "activity_ID": "c47ac10b-58cc-4372-a567-0e02b2c3d510",
  "project_ID": "b47ac10b-58cc-4372-a567-0e02b2c3d500",
  "task": "Developing",
  "taskDetails": "Implemented new authentication features for Cordys",
  "isBillable": true,
  "status": "Draft"
}

###

### 10. POST - Create Timesheet for Different Project
POST http://localhost:4004/odata/v4/employee/MyTimesheets
Authorization: Basic nadeem.abbas:initial
Content-Type: application/json

{
  "employee_ID": "a47ac10b-58cc-4372-a567-0e02b2c3d491",
  "workDate": "2024-11-04",
  "hoursWorked": 8.0,
  "activity_ID": "c47ac10b-58cc-4372-a567-0e02b2c3d520",
  "project_ID": "b47ac10b-58cc-4372-a567-0e02b2c3d501",
  "task": "Designing",
  "taskDetails": "Created UI mockups for Sony COFA new module",
  "isBillable": true,
  "status": "Draft"
}

###

### 11. POST - Create Non-Project Timesheet (Leave)
POST http://localhost:4004/odata/v4/employee/MyTimesheets
Authorization: Basic yugal.kishore:initial
Content-Type: application/json

{
  "employee_ID": "a47ac10b-58cc-4372-a567-0e02b2c3d492",
  "workDate": "2024-11-05",
  "hoursWorked": 8.0,
  "nonProjectType_ID": "n47ac10b-58cc-4372-a567-0e02b2c3d562",
  "task": "Leave",
  "taskDetails": "Sick leave",
  "isBillable": false,
  "status": "Draft"
}

###

### 12. PATCH - Update Draft Timesheet
PATCH http://localhost:4004/odata/v4/employee/MyTimesheets(d47ac10b-58cc-4372-a567-0e02b2c3d524)
Authorization: Basic aditya.mishra:initial
Content-Type: application/json

{
  "employee_ID": "a47ac10b-58cc-4372-a567-0e02b2c3d490",
  "hoursWorked": 7.5,
  "taskDetails": "Updated: Created data visualization components with React charts"
}

###

### 13. PATCH - Update Approved Timesheet (New Feature)
PATCH http://localhost:4004/odata/v4/employee/MyTimesheets(d47ac10b-58cc-4372-a567-0e02b2c3d520)
Authorization: Basic aditya.mishra:initial
Content-Type: application/json

{
  "hoursWorked": 8.5,
  "taskDetails": "Updated after approval: Added additional UI enhancements"
}

###

### 14. POST - Submit Timesheet Action  
POST http://localhost:34909/odata/v4/employee/submitTimesheet
Authorization: Basic aditya.mishra:initial
Content-Type: application/json

{
  "timesheetID": "TS002"
}

###

### 15. POST - Update Timesheet Action
POST http://localhost:4004/odata/v4/employee/updateTimesheet
Authorization: Basic aditya.mishra:initial
Content-Type: application/json

{
  "timesheetID": "TS009",
  "hours": 7.0,
  "taskDetails": "Refined data visualization components"
}

###

### 16. POST - Validate Daily Hours Function
POST http://localhost:4004/odata/v4/employee/validateDailyHours
Authorization: Basic aditya.mishra:initial
Content-Type: application/json

{
  "date": "2024-10-28"
}

###

### 17. DELETE - Delete Draft Timesheet
DELETE http://localhost:4004/odata/v4/employee/MyTimesheets(d47ac10b-58cc-4372-a567-0e02b2c3d529)
Authorization: Basic aditya.mishra:initial

###

### 18. GET - Read Single Timesheet by ID
GET http://localhost:4004/odata/v4/employee/MyTimesheets(d47ac10b-58cc-4372-a567-0e02b2c3d520)
Authorization: Basic aditya.mishra:initial

###

### 19. GET - Read Timesheets with Filter (By Date)
GET http://localhost:4004/odata/v4/employee/MyTimesheets?$filter=workDate eq 2024-10-28
Authorization: Basic aditya.mishra:initial

###

### 20. GET - Read Timesheets with Filter (By Status)
GET http://localhost:4004/odata/v4/employee/MyTimesheets?$filter=status eq 'Approved'
Authorization: Basic aditya.mishra:initial
###

### 21. POST - Create Multiple Timesheets for Same Day (Testing 15-hour limit)
POST http://localhost:4004/odata/v4/employee/MyTimesheets
Authorization: Basic aditya.mishra:initial
Content-Type: application/json

{
  "employee_ID": "a47ac10b-58cc-4372-a567-0e02b2c3d490",
  "workDate": "2024-11-04",
  "hoursWorked": 8.0,
  "activity_ID": "c47ac10b-58cc-4372-a567-0e02b2c3d511",
  "project_ID": "b47ac10b-58cc-4372-a567-0e02b2c3d500",
  "task": "Developing",
  "taskDetails": "CAPI development for Cordys",
  "isBillable": true,
  "status": "Draft"
}

###

### 22. GET - Expand Timesheet with Related Entities
GET http://localhost:4004/odata/v4/employee/MyTimesheets?$expand=activity,project,employee
Authorization: Basic aditya.mishra:initial

###

### 23. POST - Test Validation: Exceeding 15 hours
POST http://localhost:4004/odata/v4/employee/MyTimesheets
Authorization: Basic aditya.mishra:initial
Content-Type: application/json

{
  "employee_ID": "a47ac10b-58cc-4372-a567-0e02b2c3d490",
  "workDate": "2024-11-04",
  "hoursWorked": 16.0,
  "activity_ID": "c47ac10b-58cc-4372-a567-0e02b2c3d510",
  "task": "Developing",
  "taskDetails": "This should fail - exceeds 15 hours",
  "isBillable": true
}

###

### 24. POST - Create Timesheet with Bug Fix Task
POST http://localhost:4004/odata/v4/employee/MyTimesheets
Authorization: Basic aditya.mishra:initial
Content-Type: application/json

{
  "employee_ID": "a47ac10b-58cc-4372-a567-0e02b2c3d490",
  "workDate": "2024-11-05",
  "hoursWorked": 6.0,
  "activity_ID": "c47ac10b-58cc-4372-a567-0e02b2c3d512",
  "project_ID": "b47ac10b-58cc-4372-a567-0e02b2c3d500",
  "task": "Bug Fix",
  "taskDetails": "Fixed critical production bug in Cordys authentication",
  "isBillable": true,
  "status": "Draft"
}

###

### 25. POST - Create Timesheet with Client Call Task
POST http://localhost:4004/odata/v4/employee/MyTimesheets
Authorization: Basic EMP002:password
Content-Type: application/json

{
  "employee_ID": "a47ac10b-58cc-4372-a567-0e02b2c3d490",
  "workDate": "2024-11-05",
  "hoursWorked": 2.0,
  "activity_ID": "c47ac10b-58cc-4372-a567-0e02b2c3d523",
  "project_ID": "b47ac10b-58cc-4372-a567-0e02b2c3d501",
  "task": "Client Call",
  "taskDetails": "Weekly sync meeting with Sony COFA stakeholders",
  "isBillable": true,
  "status": "Draft"
}

###